### ISSUE TITLE
Add a rollback feature to the setup script.

### ISSUE THREAD

**Issue by kerk12** [kerk12/VMInit#4]
We need a rollback feature, so that if the installation fails, the copied files get deleted (so that any unusable files aren't left back). Maybe add a log as well?

**Comment by hpanago** [comment]
Nice thought.

Could you elaborate about the log? Formatting, information, place to be kept, etc.

Thanks :)

**Comment by kerk12** [comment]
It needs the timestamp and the error message. Now the location, it could be something like the usual ```/var/log/vminit```, or something like that. Always open to suggestions.
