### ISSUE TITLE
init demon works only for sysvinit systems

### ISSUE THREAD

**Issue by hpanago** [kerk12/VMInit#6]
I would like a write the VMInit.service file.  Meaning, a systemd startup script.

May I?

**Comment by kerk12** [comment]
Sure, go ahead.

**Comment by kerk12** [comment]
I updated the script to use systemd. Now there needs to be a workaround for the script to work in case systemd doesn't run on the system. Maybe a check whether systemd exists and runs?

**Comment by hpanago** [comment]
Sure, even something like "ls -l  /proc/1/exe" could do the trick.

**Comment by hpanago** [comment]
But then you will need the file for sysvinit, which you deleted (?). 
And also, about the service file https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my.
Guess it depends.

**Comment by kerk12** [comment]
It's still there but it doesn't get copied rn, as it is. As for bin/env, the service is run by root, so it'll execute whatever is in root's PATH. Most of the times, it doesn't get modified so there should be no issue.

**Comment by kerk12** [comment]
Also, `ps --no-headers -o comm 1` is better for parsing.
