### ISSUE TITLE
vboxmanage does not find VMs

### ISSUE THREAD

**Issue by hpanago** [kerk12/VMInit#7]
Looks like the daemon runs as root and thus when the VMs are owned by a simple user the daemon runs the command "vboxmanage list runningvms/vms" and gets nothing in return( because root owns no VMs).

How have you made this work for you?

**Comment by kerk12** [comment]
@hpanago I had my VMs running as root. I could add a "user" configuration option to sudo as the user.

**Comment by hpanago** [comment]
If you sudo the command  I mentioned above it still gets the root's VMs.

**Comment by kerk12** [comment]
I'll need to investigate. Please give me some time...

**Comment by kerk12** [comment]
@hpanago I added an option to run the commands as a non-root user. Check the new, default [vmlist.txt](https://github.com/kerk12/VMInit/blob/master/vmlist.txt) for more info. I'm closing the issue. Please reopen if it persists.
